name: App CI/CD Workflow

on:

  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
      - '*.jpeg'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
      - '*.jpeg'
jobs:
  mobile:
    uses: cvch29/challenge-templates/.github/workflows/ci-cd-mobile.yaml@main
    with:
      environment: challenge 